all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    node1<host dns>:
      ansible_host: 0.0.0.0 
      # node1 host ip
    node2<host dns>:
      ansible_host: 0.0.0.0 
      # node2 host ip
    node3<host dns>:
      ansible_host: 0.0.0.0 
      # node3 host ip

  children:
    prometheus_server:
      hosts:
        node1<host dns>:
        node2<host dns>:
        node3<host dns>:
    node_exporters:
      hosts:
        node1<host dns>:
        node2<host dns>:
        node3<host dns>:

